// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: MembershipRequest.proto

package protobuf

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MembershipReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// src address
	SourceAddress          string   `protobuf:"bytes,1,opt,name=sourceAddress,proto3" json:"sourceAddress,omitempty"`
	Command                uint32   `protobuf:"varint,2,opt,name=command,proto3" json:"command,omitempty"`
	MembersList            []string `protobuf:"bytes,3,rep,name=membersList,proto3" json:"membersList,omitempty"`
	JoinDestinationAddress *string  `protobuf:"bytes,4,opt,name=joinDestinationAddress,proto3,oneof" json:"joinDestinationAddress,omitempty"`
}

func (x *MembershipReq) Reset() {
	*x = MembershipReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MembershipRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MembershipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipReq) ProtoMessage() {}

func (x *MembershipReq) ProtoReflect() protoreflect.Message {
	mi := &file_MembershipRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipReq.ProtoReflect.Descriptor instead.
func (*MembershipReq) Descriptor() ([]byte, []int) {
	return file_MembershipRequest_proto_rawDescGZIP(), []int{0}
}

func (x *MembershipReq) GetSourceAddress() string {
	if x != nil {
		return x.SourceAddress
	}
	return ""
}

func (x *MembershipReq) GetCommand() uint32 {
	if x != nil {
		return x.Command
	}
	return 0
}

func (x *MembershipReq) GetMembersList() []string {
	if x != nil {
		return x.MembersList
	}
	return nil
}

func (x *MembershipReq) GetJoinDestinationAddress() string {
	if x != nil && x.JoinDestinationAddress != nil {
		return *x.JoinDestinationAddress
	}
	return ""
}

var File_MembershipRequest_proto protoreflect.FileDescriptor

var file_MembershipRequest_proto_rawDesc = []byte{
	0x0a, 0x17, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x22, 0xc9, 0x01, 0x0a, 0x0d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x16, 0x6a, 0x6f, 0x69, 0x6e, 0x44,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x16, 0x6a, 0x6f, 0x69, 0x6e, 0x44,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x88, 0x01, 0x01, 0x42, 0x19, 0x0a, 0x17, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x44, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42,
	0x0d, 0x5a, 0x0b, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MembershipRequest_proto_rawDescOnce sync.Once
	file_MembershipRequest_proto_rawDescData = file_MembershipRequest_proto_rawDesc
)

func file_MembershipRequest_proto_rawDescGZIP() []byte {
	file_MembershipRequest_proto_rawDescOnce.Do(func() {
		file_MembershipRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_MembershipRequest_proto_rawDescData)
	})
	return file_MembershipRequest_proto_rawDescData
}

var file_MembershipRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_MembershipRequest_proto_goTypes = []interface{}{
	(*MembershipReq)(nil), // 0: protobuf.MembershipReq
}
var file_MembershipRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_MembershipRequest_proto_init() }
func file_MembershipRequest_proto_init() {
	if File_MembershipRequest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MembershipRequest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MembershipReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_MembershipRequest_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MembershipRequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MembershipRequest_proto_goTypes,
		DependencyIndexes: file_MembershipRequest_proto_depIdxs,
		MessageInfos:      file_MembershipRequest_proto_msgTypes,
	}.Build()
	File_MembershipRequest_proto = out.File
	file_MembershipRequest_proto_rawDesc = nil
	file_MembershipRequest_proto_goTypes = nil
	file_MembershipRequest_proto_depIdxs = nil
}
