// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: RaftPayload.proto

package protobuf

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RaftPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type                 string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` //"requesting_a_vote","leader_ping","vote(accept/reject)",KV replication request
	SenderIP             string `protobuf:"bytes,2,opt,name=senderIP,proto3" json:"senderIP,omitempty"`
	VoteRes              string `protobuf:"bytes,3,opt,name=voteRes,proto3" json:"voteRes,omitempty"`                            // accept or reject the vote request "ACCEPT","REJECT"
	SenderTermsCompleted int32  `protobuf:"varint,4,opt,name=SenderTermsCompleted,proto3" json:"SenderTermsCompleted,omitempty"` // so if the sender has serverd less terms than you
	// you dont vote for him
	//else you do
	TermNum int32  `protobuf:"varint,5,opt,name=termNum,proto3" json:"termNum,omitempty"` // the current election term
	Log     []byte `protobuf:"bytes,6,opt,name=log,proto3" json:"log,omitempty"`          // the complete state of the system to be set by the leader
}

func (x *RaftPayload) Reset() {
	*x = RaftPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RaftPayload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaftPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftPayload) ProtoMessage() {}

func (x *RaftPayload) ProtoReflect() protoreflect.Message {
	mi := &file_RaftPayload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftPayload.ProtoReflect.Descriptor instead.
func (*RaftPayload) Descriptor() ([]byte, []int) {
	return file_RaftPayload_proto_rawDescGZIP(), []int{0}
}

func (x *RaftPayload) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RaftPayload) GetSenderIP() string {
	if x != nil {
		return x.SenderIP
	}
	return ""
}

func (x *RaftPayload) GetVoteRes() string {
	if x != nil {
		return x.VoteRes
	}
	return ""
}

func (x *RaftPayload) GetSenderTermsCompleted() int32 {
	if x != nil {
		return x.SenderTermsCompleted
	}
	return 0
}

func (x *RaftPayload) GetTermNum() int32 {
	if x != nil {
		return x.TermNum
	}
	return 0
}

func (x *RaftPayload) GetLog() []byte {
	if x != nil {
		return x.Log
	}
	return nil
}

var File_RaftPayload_proto protoreflect.FileDescriptor

var file_RaftPayload_proto_rawDesc = []byte{
	0x0a, 0x11, 0x52, 0x61, 0x66, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0xb7, 0x01,
	0x0a, 0x0b, 0x52, 0x61, 0x66, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x50, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x50, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x54, 0x65, 0x72, 0x6d, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x54, 0x65, 0x72,
	0x6d, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x65, 0x72, 0x6d, 0x4e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x65,
	0x72, 0x6d, 0x4e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_RaftPayload_proto_rawDescOnce sync.Once
	file_RaftPayload_proto_rawDescData = file_RaftPayload_proto_rawDesc
)

func file_RaftPayload_proto_rawDescGZIP() []byte {
	file_RaftPayload_proto_rawDescOnce.Do(func() {
		file_RaftPayload_proto_rawDescData = protoimpl.X.CompressGZIP(file_RaftPayload_proto_rawDescData)
	})
	return file_RaftPayload_proto_rawDescData
}

var file_RaftPayload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_RaftPayload_proto_goTypes = []interface{}{
	(*RaftPayload)(nil), // 0: protobuf.RaftPayload
}
var file_RaftPayload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RaftPayload_proto_init() }
func file_RaftPayload_proto_init() {
	if File_RaftPayload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_RaftPayload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaftPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RaftPayload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RaftPayload_proto_goTypes,
		DependencyIndexes: file_RaftPayload_proto_depIdxs,
		MessageInfos:      file_RaftPayload_proto_msgTypes,
	}.Build()
	File_RaftPayload_proto = out.File
	file_RaftPayload_proto_rawDesc = nil
	file_RaftPayload_proto_goTypes = nil
	file_RaftPayload_proto_depIdxs = nil
}
