// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: RaftShell.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaftShell struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message_ID []byte `protobuf:"bytes,1,opt,name=message_ID,json=messageID,proto3" json:"message_ID,omitempty"` //UUIDV4
	Checksum   []byte `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`                    //crcIEEE
	Payload    []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Type       string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` //"requesting_a_vote","leader_ping","vote(accept/reject)",KV replication request
}

func (x *RaftShell) Reset() {
	*x = RaftShell{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RaftShell_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaftShell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftShell) ProtoMessage() {}

func (x *RaftShell) ProtoReflect() protoreflect.Message {
	mi := &file_RaftShell_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftShell.ProtoReflect.Descriptor instead.
func (*RaftShell) Descriptor() ([]byte, []int) {
	return file_RaftShell_proto_rawDescGZIP(), []int{0}
}

func (x *RaftShell) GetMessage_ID() []byte {
	if x != nil {
		return x.Message_ID
	}
	return nil
}

func (x *RaftShell) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *RaftShell) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RaftShell) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_RaftShell_proto protoreflect.FileDescriptor

var file_RaftShell_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x52, 0x61, 0x66, 0x74, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x74, 0x0a, 0x09, 0x52,
	0x61, 0x66, 0x74, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x73, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x73, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_RaftShell_proto_rawDescOnce sync.Once
	file_RaftShell_proto_rawDescData = file_RaftShell_proto_rawDesc
)

func file_RaftShell_proto_rawDescGZIP() []byte {
	file_RaftShell_proto_rawDescOnce.Do(func() {
		file_RaftShell_proto_rawDescData = protoimpl.X.CompressGZIP(file_RaftShell_proto_rawDescData)
	})
	return file_RaftShell_proto_rawDescData
}

var file_RaftShell_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_RaftShell_proto_goTypes = []interface{}{
	(*RaftShell)(nil), // 0: protobuf.RaftShell
}
var file_RaftShell_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RaftShell_proto_init() }
func file_RaftShell_proto_init() {
	if File_RaftShell_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_RaftShell_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaftShell); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RaftShell_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RaftShell_proto_goTypes,
		DependencyIndexes: file_RaftShell_proto_depIdxs,
		MessageInfos:      file_RaftShell_proto_msgTypes,
	}.Build()
	File_RaftShell_proto = out.File
	file_RaftShell_proto_rawDesc = nil
	file_RaftShell_proto_goTypes = nil
	file_RaftShell_proto_depIdxs = nil
}
