// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: replicationShell.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepShell struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message_ID []byte `protobuf:"bytes,1,opt,name=message_ID,json=messageID,proto3" json:"message_ID,omitempty"` //UUIDV4
	Checksum   uint64 `protobuf:"varint,2,opt,name=checksum,proto3" json:"checksum,omitempty"`                   //crcIEEE
	Payload    []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *RepShell) Reset() {
	*x = RepShell{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replicationShell_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepShell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepShell) ProtoMessage() {}

func (x *RepShell) ProtoReflect() protoreflect.Message {
	mi := &file_replicationShell_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepShell.ProtoReflect.Descriptor instead.
func (*RepShell) Descriptor() ([]byte, []int) {
	return file_replicationShell_proto_rawDescGZIP(), []int{0}
}

func (x *RepShell) GetMessage_ID() []byte {
	if x != nil {
		return x.Message_ID
	}
	return nil
}

func (x *RepShell) GetChecksum() uint64 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *RepShell) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_replicationShell_proto protoreflect.FileDescriptor

var file_replicationShell_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x68, 0x65,
	0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x22, 0x5f, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x12, 0x1d,
	0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_replicationShell_proto_rawDescOnce sync.Once
	file_replicationShell_proto_rawDescData = file_replicationShell_proto_rawDesc
)

func file_replicationShell_proto_rawDescGZIP() []byte {
	file_replicationShell_proto_rawDescOnce.Do(func() {
		file_replicationShell_proto_rawDescData = protoimpl.X.CompressGZIP(file_replicationShell_proto_rawDescData)
	})
	return file_replicationShell_proto_rawDescData
}

var file_replicationShell_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_replicationShell_proto_goTypes = []interface{}{
	(*RepShell)(nil), // 0: protobuf.RepShell
}
var file_replicationShell_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_replicationShell_proto_init() }
func file_replicationShell_proto_init() {
	if File_replicationShell_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_replicationShell_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepShell); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_replicationShell_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_replicationShell_proto_goTypes,
		DependencyIndexes: file_replicationShell_proto_depIdxs,
		MessageInfos:      file_replicationShell_proto_msgTypes,
	}.Build()
	File_replicationShell_proto = out.File
	file_replicationShell_proto_rawDesc = nil
	file_replicationShell_proto_goTypes = nil
	file_replicationShell_proto_depIdxs = nil
}
